In [177]:
import pandas as pd

In [178]:
df18= pd.read_csv("138_202203_sehirtiyatrolar2018.csv",sep=";")

In [179]:
df18["doluluk_orani_%"]=df18["gun"]

In [180]:
df18

,tarih,gun,saat,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,24.10.2018,Salı,20.0,Abdülhamid Ateş Çemberi,100%,751,Salı
1,23.10.2018,Çarşamba,20.0,Abdülhamid Ateş Çemberi,96%,745,Çarşamba
2,29.10.2018,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,98%,748,Pazartesi
3,30.10.2018,Salı,20.0,Asım Bir Varoluş Mücadelesi,76%,590,Salı
4,05.11.2018,Pazartesi,20.0,Bir Yunus Hikayesi,89%,675,Pazartesi
5,06.11.2018,Salı,20.0,Bir Yunus Hikayesi,61%,469,Salı
6,12.11.2018,Pazartesi,20.0,Abdülhamid Ateş Çemberi,100%,769,Pazartesi
7,19.11.2018,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,43%,331,Pazartesi
8,20.11.2018,Salı,20.0,Asım Bir Varoluş Mücadelesi,58%,437,Salı
9,27.11.2018,Salı,19.3,Bir Yunus Hikayesi,57%,432,Salı
10,28.11.2018,Çarşamba,20.0,Bir Yunus Hikayesi,51%,389,Çarşamba
11,03.12.2018,Pazartesi,20.0,Abdülhamid Ateş Çemberi,100%,752,Pazartesi
12,04.12.2018,Salı,20.0,Abdülhamid Ateş Çemberi,100%,759,Salı
13,10.12.2018,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,64%,488,Pazartesi
14,11.12.2018,Salı,20.0,Asım Bir Varoluş Mücadelesi,72%,544,Salı
15,24.12.2018,Pazartesi,20.0,Bir Yunus Hikayesi,58%,438,Pazartesi
16,25.12.2018,Salı,20.0,Bir Yunus Hikayesi,49%,374,Salı
17,27.12. 2018,Perşembe,19.3,Asım Bir Varoluş Mücadelesi,98%,746,Perşembe

In [181]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     object
 1   gun              18 non-null     object
 2   saat             18 non-null     float64
 3   oyun             18 non-null     object
 4   doluluk_orani    18 non-null     object
 5   izleyici_sayisi  18 non-null     int64
 6   doluluk_orani_%  18 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 1.1+ KB

In [182]:
df18["tarih"]=df18["tarih"].astype("string")

In [183]:
for x in df18["tarih"].index:
    df18["tarih"][x]=df18["tarih"][x].replace(" ","")
    df18["tarih"][x]=df18["tarih"][x].replace(".","-")

In [184]:
df18["tarih"] = pd.to_datetime(df18["tarih"])

C:\Users\User\AppData\Local\Temp\ipykernel_15084\1783362938.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df18["tarih"] = pd.to_datetime(df18["tarih"])

In [185]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   gun              18 non-null     object
 2   saat             18 non-null     float64
 3   oyun             18 non-null     object
 4   doluluk_orani    18 non-null     object
 5   izleyici_sayisi  18 non-null     int64
 6   doluluk_orani_%  18 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [186]:
for x in df18["doluluk_orani_%"].index:
    df18["doluluk_orani_%"][x]=df18["doluluk_orani"][x].replace("%","")

C:\Users\User\AppData\Local\Temp\ipykernel_15084\2877559731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df18["doluluk_orani_%"][x]=df18["doluluk_orani"][x].replace("%","")

In [187]:
df18

,tarih,gun,saat,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,2018-10-24,Salı,20.0,Abdülhamid Ateş Çemberi,100%,751,100
1,2018-10-23,Çarşamba,20.0,Abdülhamid Ateş Çemberi,96%,745,96
2,2018-10-29,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,98%,748,98
3,2018-10-30,Salı,20.0,Asım Bir Varoluş Mücadelesi,76%,590,76
4,2018-05-11,Pazartesi,20.0,Bir Yunus Hikayesi,89%,675,89
5,2018-06-11,Salı,20.0,Bir Yunus Hikayesi,61%,469,61
6,2018-12-11,Pazartesi,20.0,Abdülhamid Ateş Çemberi,100%,769,100
7,2018-11-19,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,43%,331,43
8,2018-11-20,Salı,20.0,Asım Bir Varoluş Mücadelesi,58%,437,58
9,2018-11-27,Salı,19.3,Bir Yunus Hikayesi,57%,432,57
10,2018-11-28,Çarşamba,20.0,Bir Yunus Hikayesi,51%,389,51
11,2018-03-12,Pazartesi,20.0,Abdülhamid Ateş Çemberi,100%,752,100
12,2018-04-12,Salı,20.0,Abdülhamid Ateş Çemberi,100%,759,100
13,2018-10-12,Pazartesi,20.0,Asım Bir Varoluş Mücadelesi,64%,488,64
14,2018-11-12,Salı,20.0,Asım Bir Varoluş Mücadelesi,72%,544,72
15,2018-12-24,Pazartesi,20.0,Bir Yunus Hikayesi,58%,438,58
16,2018-12-25,Salı,20.0,Bir Yunus Hikayesi,49%,374,49
17,2018-12-27,Perşembe,19.3,Asım Bir Varoluş Mücadelesi,98%,746,98

In [188]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   gun              18 non-null     object
 2   saat             18 non-null     float64
 3   oyun             18 non-null     object
 4   doluluk_orani    18 non-null     object
 5   izleyici_sayisi  18 non-null     int64
 6   doluluk_orani_%  18 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [189]:
df18["doluluk_orani_%"]=df18["doluluk_orani_%"].astype("float64")

In [190]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   gun              18 non-null     object
 2   saat             18 non-null     float64
 3   oyun             18 non-null     object
 4   doluluk_orani    18 non-null     object
 5   izleyici_sayisi  18 non-null     int64
 6   doluluk_orani_%  18 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [191]:
df18["saat"] = pd.to_timedelta(df18["saat"] ,unit="h")

In [192]:
for x in df18["tarih"].index:
    df18["tarih"][x]=df18["tarih"][x]+df18["saat"][x]

C:\Users\User\AppData\Local\Temp\ipykernel_15084\456833891.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df18["tarih"][x]=df18["tarih"][x]+df18["saat"][x]

In [193]:
df18

,tarih,gun,saat,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,2018-10-24 20:00:00,Salı,0 days 20:00:00,Abdülhamid Ateş Çemberi,100%,751,100.0
1,2018-10-23 20:00:00,Çarşamba,0 days 20:00:00,Abdülhamid Ateş Çemberi,96%,745,96.0
2,2018-10-29 20:00:00,Pazartesi,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,98%,748,98.0
3,2018-10-30 20:00:00,Salı,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,76%,590,76.0
4,2018-05-11 20:00:00,Pazartesi,0 days 20:00:00,Bir Yunus Hikayesi,89%,675,89.0
5,2018-06-11 20:00:00,Salı,0 days 20:00:00,Bir Yunus Hikayesi,61%,469,61.0
6,2018-12-11 20:00:00,Pazartesi,0 days 20:00:00,Abdülhamid Ateş Çemberi,100%,769,100.0
7,2018-11-19 20:00:00,Pazartesi,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,43%,331,43.0
8,2018-11-20 20:00:00,Salı,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,58%,437,58.0
9,2018-11-27 19:18:00,Salı,0 days 19:18:00,Bir Yunus Hikayesi,57%,432,57.0
10,2018-11-28 20:00:00,Çarşamba,0 days 20:00:00,Bir Yunus Hikayesi,51%,389,51.0
11,2018-03-12 20:00:00,Pazartesi,0 days 20:00:00,Abdülhamid Ateş Çemberi,100%,752,100.0
12,2018-04-12 20:00:00,Salı,0 days 20:00:00,Abdülhamid Ateş Çemberi,100%,759,100.0
13,2018-10-12 20:00:00,Pazartesi,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,64%,488,64.0
14,2018-11-12 20:00:00,Salı,0 days 20:00:00,Asım Bir Varoluş Mücadelesi,72%,544,72.0
15,2018-12-24 20:00:00,Pazartesi,0 days 20:00:00,Bir Yunus Hikayesi,58%,438,58.0
16,2018-12-25 20:00:00,Salı,0 days 20:00:00,Bir Yunus Hikayesi,49%,374,49.0
17,2018-12-27 19:18:00,Perşembe,0 days 19:18:00,Asım Bir Varoluş Mücadelesi,98%,746,98.0

In [194]:
df18=df18.drop(columns="gun")

In [195]:
df18=df18.drop(columns="saat")

In [196]:
list=[]
list1=[]

for x in df18["doluluk_orani_%"].index:
    list.append(df18["doluluk_orani_%"][x])
    list1.append(df18["izleyici_sayisi"][x])

In [197]:
list

[100.0,
 96.0,
 98.0,
 76.0,
 89.0,
 61.0,
 100.0,
 43.0,
 58.0,
 57.0,
 51.0,
 100.0,
 100.0,
 64.0,
 72.0,
 58.0,
 49.0,
 98.0]

In [198]:
list1

[751,
 745,
 748,
 590,
 675,
 469,
 769,
 331,
 437,
 432,
 389,
 752,
 759,
 488,
 544,
 438,
 374,
 746]

In [199]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   oyun             18 non-null     object
 2   doluluk_orani    18 non-null     object
 3   izleyici_sayisi  18 non-null     int64
 4   doluluk_orani_%  18 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 852.0+ bytes

In [200]:
doluluk_oranı=[]
for x in df18["doluluk_orani_%"].index:

    df18["doluluk_orani_%"][x]=(list1[x]/list[x])*100
    doluluk_oranı.append(df18["doluluk_orani_%"][x])

C:\Users\User\AppData\Local\Temp\ipykernel_15084\2079297700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df18["doluluk_orani_%"][x]=(list1[x]/list[x])*100

In [201]:
df18

,tarih,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,2018-10-24 20:00:00,Abdülhamid Ateş Çemberi,100%,751,751.000000
1,2018-10-23 20:00:00,Abdülhamid Ateş Çemberi,96%,745,776.041667
2,2018-10-29 20:00:00,Asım Bir Varoluş Mücadelesi,98%,748,763.265306
3,2018-10-30 20:00:00,Asım Bir Varoluş Mücadelesi,76%,590,776.315789
4,2018-05-11 20:00:00,Bir Yunus Hikayesi,89%,675,758.426966
5,2018-06-11 20:00:00,Bir Yunus Hikayesi,61%,469,768.852459
6,2018-12-11 20:00:00,Abdülhamid Ateş Çemberi,100%,769,769.000000
7,2018-11-19 20:00:00,Asım Bir Varoluş Mücadelesi,43%,331,769.767442
8,2018-11-20 20:00:00,Asım Bir Varoluş Mücadelesi,58%,437,753.448276
9,2018-11-27 19:18:00,Bir Yunus Hikayesi,57%,432,757.894737
10,2018-11-28 20:00:00,Bir Yunus Hikayesi,51%,389,762.745098
11,2018-03-12 20:00:00,Abdülhamid Ateş Çemberi,100%,752,752.000000
12,2018-04-12 20:00:00,Abdülhamid Ateş Çemberi,100%,759,759.000000
13,2018-10-12 20:00:00,Asım Bir Varoluş Mücadelesi,64%,488,762.500000
14,2018-11-12 20:00:00,Asım Bir Varoluş Mücadelesi,72%,544,755.555556
15,2018-12-24 20:00:00,Bir Yunus Hikayesi,58%,438,755.172414
16,2018-12-25 20:00:00,Bir Yunus Hikayesi,49%,374,763.265306
17,2018-12-27 19:18:00,Asım Bir Varoluş Mücadelesi,98%,746,761.224490

In [202]:
x

17

In [203]:
xx=sum(df18["doluluk_orani_%"])

In [204]:
xx=xx/18
xx

761.970861413456

In [205]:
for x in df18["doluluk_orani_%"].index:
    df18["doluluk_orani_%"][x]=(df18["doluluk_orani_%"][x]/df18["izleyici_sayisi"][x])

C:\Users\User\AppData\Local\Temp\ipykernel_15084\1486510706.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df18["doluluk_orani_%"][x]=(df18["doluluk_orani_%"][x]/df18["izleyici_sayisi"][x])

In [206]:
for t in df18["doluluk_orani_%"].index:

    df18["doluluk_orani_%"][t]=(list1[t]/xx)*100

C:\Users\User\AppData\Local\Temp\ipykernel_15084\2773331913.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df18["doluluk_orani_%"][t]=(list1[t]/xx)*100

In [207]:
df18

,tarih,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,2018-10-24 20:00:00,Abdülhamid Ateş Çemberi,100%,751,98.560199
1,2018-10-23 20:00:00,Abdülhamid Ateş Çemberi,96%,745,97.772768
2,2018-10-29 20:00:00,Asım Bir Varoluş Mücadelesi,98%,748,98.166484
3,2018-10-30 20:00:00,Asım Bir Varoluş Mücadelesi,76%,590,77.430782
4,2018-05-11 20:00:00,Bir Yunus Hikayesi,89%,675,88.586065
5,2018-06-11 20:00:00,Bir Yunus Hikayesi,61%,469,61.550910
6,2018-12-11 20:00:00,Abdülhamid Ateş Çemberi,100%,769,100.922494
7,2018-11-19 20:00:00,Asım Bir Varoluş Mücadelesi,43%,331,43.439981
8,2018-11-20 20:00:00,Asım Bir Varoluş Mücadelesi,58%,437,57.351274
9,2018-11-27 19:18:00,Bir Yunus Hikayesi,57%,432,56.695081
10,2018-11-28 20:00:00,Bir Yunus Hikayesi,51%,389,51.051821
11,2018-03-12 20:00:00,Abdülhamid Ateş Çemberi,100%,752,98.691438
12,2018-04-12 20:00:00,Abdülhamid Ateş Çemberi,100%,759,99.610108
13,2018-10-12 20:00:00,Asım Bir Varoluş Mücadelesi,64%,488,64.044444
14,2018-11-12 20:00:00,Asım Bir Varoluş Mücadelesi,72%,544,71.393806
15,2018-12-24 20:00:00,Bir Yunus Hikayesi,58%,438,57.482513
16,2018-12-25 20:00:00,Bir Yunus Hikayesi,49%,374,49.083242
17,2018-12-27 19:18:00,Asım Bir Varoluş Mücadelesi,98%,746,97.904006

In [208]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   oyun             18 non-null     object
 2   doluluk_orani    18 non-null     object
 3   izleyici_sayisi  18 non-null     int64
 4   doluluk_orani_%  18 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 852.0+ bytes

In [209]:
doluluk_oranı

[751.0,
 776.0416666666667,
 763.265306122449,
 776.3157894736843,
 758.4269662921348,
 768.8524590163935,
 769.0,
 769.7674418604652,
 753.448275862069,
 757.8947368421052,
 762.7450980392157,
 752.0,
 759.0,
 762.5,
 755.5555555555555,
 755.1724137931035,
 763.265306122449,
 761.2244897959184]

In [210]:
df18["doluluk_orani"]=df18["doluluk_orani"].astype("string")

In [211]:
for ara in df18["doluluk_orani_%"].index:
    if df18["doluluk_orani"][ara]=="100%":
        doluluk_oranı.pop(ara)

In [212]:
sum(doluluk_oranı)/len(doluluk_oranı)

762.6454035563314

In [213]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   oyun             18 non-null     object
 2   doluluk_orani    18 non-null     string
 3   izleyici_sayisi  18 non-null     int64
 4   doluluk_orani_%  18 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1), string(1)
memory usage: 852.0+ bytes

In [214]:
df18["oyun"]=df18["oyun"].astype("string")

In [215]:
df18

,tarih,oyun,doluluk_orani,izleyici_sayisi,doluluk_orani_%
0,2018-10-24 20:00:00,Abdülhamid Ateş Çemberi,100%,751,98.560199
1,2018-10-23 20:00:00,Abdülhamid Ateş Çemberi,96%,745,97.772768
2,2018-10-29 20:00:00,Asım Bir Varoluş Mücadelesi,98%,748,98.166484
3,2018-10-30 20:00:00,Asım Bir Varoluş Mücadelesi,76%,590,77.430782
4,2018-05-11 20:00:00,Bir Yunus Hikayesi,89%,675,88.586065
5,2018-06-11 20:00:00,Bir Yunus Hikayesi,61%,469,61.550910
6,2018-12-11 20:00:00,Abdülhamid Ateş Çemberi,100%,769,100.922494
7,2018-11-19 20:00:00,Asım Bir Varoluş Mücadelesi,43%,331,43.439981
8,2018-11-20 20:00:00,Asım Bir Varoluş Mücadelesi,58%,437,57.351274
9,2018-11-27 19:18:00,Bir Yunus Hikayesi,57%,432,56.695081
10,2018-11-28 20:00:00,Bir Yunus Hikayesi,51%,389,51.051821
11,2018-03-12 20:00:00,Abdülhamid Ateş Çemberi,100%,752,98.691438
12,2018-04-12 20:00:00,Abdülhamid Ateş Çemberi,100%,759,99.610108
13,2018-10-12 20:00:00,Asım Bir Varoluş Mücadelesi,64%,488,64.044444
14,2018-11-12 20:00:00,Asım Bir Varoluş Mücadelesi,72%,544,71.393806
15,2018-12-24 20:00:00,Bir Yunus Hikayesi,58%,438,57.482513
16,2018-12-25 20:00:00,Bir Yunus Hikayesi,49%,374,49.083242
17,2018-12-27 19:18:00,Asım Bir Varoluş Mücadelesi,98%,746,97.904006

In [216]:
df18 = df18.drop(columns="doluluk_orani")

In [217]:
df18

,tarih,oyun,izleyici_sayisi,doluluk_orani_%
0,2018-10-24 20:00:00,Abdülhamid Ateş Çemberi,751,98.560199
1,2018-10-23 20:00:00,Abdülhamid Ateş Çemberi,745,97.772768
2,2018-10-29 20:00:00,Asım Bir Varoluş Mücadelesi,748,98.166484
3,2018-10-30 20:00:00,Asım Bir Varoluş Mücadelesi,590,77.430782
4,2018-05-11 20:00:00,Bir Yunus Hikayesi,675,88.586065
5,2018-06-11 20:00:00,Bir Yunus Hikayesi,469,61.550910
6,2018-12-11 20:00:00,Abdülhamid Ateş Çemberi,769,100.922494
7,2018-11-19 20:00:00,Asım Bir Varoluş Mücadelesi,331,43.439981
8,2018-11-20 20:00:00,Asım Bir Varoluş Mücadelesi,437,57.351274
9,2018-11-27 19:18:00,Bir Yunus Hikayesi,432,56.695081
10,2018-11-28 20:00:00,Bir Yunus Hikayesi,389,51.051821
11,2018-03-12 20:00:00,Abdülhamid Ateş Çemberi,752,98.691438
12,2018-04-12 20:00:00,Abdülhamid Ateş Çemberi,759,99.610108
13,2018-10-12 20:00:00,Asım Bir Varoluş Mücadelesi,488,64.044444
14,2018-11-12 20:00:00,Asım Bir Varoluş Mücadelesi,544,71.393806
15,2018-12-24 20:00:00,Bir Yunus Hikayesi,438,57.482513
16,2018-12-25 20:00:00,Bir Yunus Hikayesi,374,49.083242
17,2018-12-27 19:18:00,Asım Bir Varoluş Mücadelesi,746,97.904006

In [218]:
df18.to_excel("temiz_konya_sehir_tiyatro_excel_18.xlsx",header=True ,index=False)

In [219]:
df18.to_csv("temiz_konya_sehir_tiyatro_csv_18.csv",header=True ,index=False)

In [221]:
df18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tarih            18 non-null     datetime64[ns]
 1   oyun             18 non-null     string
 2   izleyici_sayisi  18 non-null     int64
 3   doluluk_orani_%  18 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), string(1)
memory usage: 708.0 bytes